import { Injectable } from '@angular/core';
import { ResourcesService } from './resources.service';
import { ResourceType } from '../models/resource.model';

/**
 * MarketService - PLACEHOLDER
 *
 * IMPORTANT: This service is NOT currently active in the game loop.
 * NO automatic selling of Metal or Plastic occurs.
 * Money is ONLY generated by Empaquetadora (Components -> Money).
 *
 * This service may be activated in the future via:
 * - Manual player toggle
 * - Upgrade unlock
 * - Event trigger
 *
 * DO NOT inject or call from GameLoopService.
 */
@Injectable({
  providedIn: 'root',
})
export class MarketService {
  // Base prices according to MVP_BALANCING_TABLE (for future use)
  private readonly METAL_PRICE = 2;
  private readonly PLASTIC_PRICE = 2;
  private readonly COMPONENTS_PRICE = 3; // Early game: 1 component = 2 money

  constructor(private resourcesService: ResourcesService) {}

  /**
   * NOT CALLED - Placeholder for future auto-sell functionality.
   * Would automatically sell all available Metal and Plastic.
   */
  processAutoSell(): void {
    // DISABLED - Do not execute
    // this.sellResource(ResourceType.METAL, this.METAL_PRICE);
    // this.sellResource(ResourceType.PLASTIC, this.PLASTIC_PRICE);
  }

  private sellResource(resourceId: string, pricePerUnit: number): void {
    const amount = this.resourcesService.getAmount(resourceId);
    if (amount <= 0) return;

    const success = this.resourcesService.subtract(resourceId, amount);
    if (success) {
      const moneyEarned = amount * pricePerUnit;
      this.resourcesService.add(ResourceType.MONEY, moneyEarned);
    }
  }

  // Future: event-based price modifiers can be added here
  getPrice(resourceId: string): number {
    if (resourceId === ResourceType.METAL) return this.METAL_PRICE;
    if (resourceId === ResourceType.PLASTIC) return this.PLASTIC_PRICE;
    if (resourceId === ResourceType.COMPONENTS) return this.COMPONENTS_PRICE;
    return 0;
  }

  /**
   * Manual sell components for money.
   * Used in early game before Empaquetadora is unlocked.
   * @param amount Number of components to sell
   * @returns true if sale was successful, false otherwise
   */
  sellComponents(amount: number): boolean {
    if (!this.resourcesService.hasEnough(ResourceType.COMPONENTS, amount)) {
      return false;
    }

    const success = this.resourcesService.subtract(ResourceType.COMPONENTS, amount);
    if (success) {
      const moneyEarned = amount * this.COMPONENTS_PRICE;
      this.resourcesService.add(ResourceType.MONEY, moneyEarned);
      return true;
    }

    return false;
  }

  sellMetal(amount: number): boolean {
    if (!this.resourcesService.hasEnough(ResourceType.METAL, amount)) {
      return false;
    }

    const success = this.resourcesService.subtract(ResourceType.METAL, amount);
    if (success) {
      const moneyEarned = amount * this.METAL_PRICE;
      this.resourcesService.add(ResourceType.MONEY, moneyEarned);
      return true;
    }

    return false;
  }
}
