import { ResourceType } from '../models/resource.model';
import { TutorialStep } from '../models/tutorial-step.model';

export const FIRST_RUN_TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'welcome',
    order: 1,
    presentation: 'modal',
    titleKey: 'tutorial.steps.welcome.title',
    bodyKey: 'tutorial.steps.welcome.body',
    confirmKey: 'tutorial.actions.start',
    completionRule: { kind: 'manual' },
  },
  {
    id: 'generate-scrap',
    order: 2,
    presentation: 'spotlight',
    titleKey: 'tutorial.steps.generate_scrap.title',
    bodyKey: 'tutorial.steps.generate_scrap.body',
    confirmKey: 'tutorial.actions.continue',
    targetId: 'scrap-button',
    completionRule: { kind: 'event', eventId: 'manual-scrap-generated' },
  },
  {
    id: 'activate-crusher',
    order: 3,
    presentation: 'spotlight',
    titleKey: 'tutorial.steps.activate_crusher.title',
    bodyKey: 'tutorial.steps.activate_crusher.body',
    confirmKey: 'tutorial.actions.continue',
    targetId: 'machine-toggle-crusher',
    completionRule: { kind: 'event', eventId: 'crusher-activated' },
  },
  {
    id: 'watch-crusher-progress',
    order: 4,
    presentation: 'spotlight',
    titleKey: 'tutorial.steps.watch_crusher_progress.title',
    bodyKey: 'tutorial.steps.watch_crusher_progress.body',
    confirmKey: 'tutorial.actions.next_step',
    targetId: 'machine-progress-crusher',
    completionRule: { kind: 'manual' },
  },
  {
    id: 'collect-metal',
    order: 5,
    presentation: 'spotlight',
    titleKey: 'tutorial.steps.collect_metal.title',
    bodyKey: 'tutorial.steps.collect_metal.body',
    confirmKey: 'tutorial.actions.next_step',
    targetId: 'resource-metal',
    completionRule: { kind: 'manual' },
  },
  {
    id: 'sell-metal',
    order: 6,
    presentation: 'spotlight',
    titleKey: 'tutorial.steps.sell_metal.title',
    bodyKey: 'tutorial.steps.sell_metal.body',
    confirmKey: 'tutorial.actions.continue',
    targetId: 'sell-metal-button',
    completionRule: { kind: 'event', eventId: 'metal-sold' },
  },
  {
    id: 'buy-first-upgrade',
    order: 7,
    presentation: 'spotlight',
    titleKey: 'tutorial.steps.buy_first_upgrade.title',
    bodyKey: 'tutorial.steps.buy_first_upgrade.body',
    confirmKey: 'tutorial.actions.continue',
    targetId: 'machine-upgrade-button-crusher',
    completionRule: { kind: 'event', eventId: 'first-upgrade-purchased' },
  },
  {
    id: 'check-next-goal',
    order: 8,
    presentation: 'inline',
    titleKey: 'tutorial.steps.check_next_goal.title',
    bodyKey: 'tutorial.steps.check_next_goal.body',
    confirmKey: 'tutorial.actions.finish',
    targetId: 'progression-hint',
    completionRule: { kind: 'manual' },
  },
  {
    id: 'complete',
    order: 9,
    presentation: 'modal',
    titleKey: 'tutorial.steps.complete.title',
    bodyKey: 'tutorial.steps.complete.body',
    confirmKey: 'tutorial.actions.close',
    completionRule: { kind: 'manual' },
  },
];