import { UpgradeDefinition, UpgradeId, UpgradeCategory } from '../models/upgrade.model';
import { ResourceType } from '../models/resource.model';
import { MachineType } from '../models/machine.model';
import { MACHINE_UPGRADE_CONFIG } from './game-balance.config';

/**
 * G) Upgrade Definitions Config
 * Based on UPGRADES_CATALOG.md - structural preparation only
 * NO logic implementation yet
 */

export const UPGRADE_DEFINITIONS: UpgradeDefinition[] = [
  // STORAGE UPGRADES
  {
    id: UpgradeId.UPG_STORE_001,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.scrap',
    baseCostMoney: 20,
    description: '+25 capacidad máxima de Chatarra por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.SCRAP,
    icon: 'assets/icons/scrap_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_002,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.metal',
    baseCostMoney: 35,
    description: '+15 capacidad máxima de Metal por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.METAL,
    icon: 'assets/icons/metal_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_003,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.plastic',
    baseCostMoney: 35,
    description: '+15 capacidad máxima de Plástico por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.PLASTIC,
    icon: 'assets/icons/plastic_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_004,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.components',
    baseCostMoney: 35,
    extraCostComponents: 1,
    description: '+5 capacidad máxima de Componentes por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.COMPONENTS,
    icon: 'assets/icons/components_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_005,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.recycled_plastic',
    baseCostMoney: 50,
    description: '+10 capacidad máxima de Plástico Reciclado por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.RECYCLED_PLASTIC,
    icon: 'assets/icons/plastic_recycle_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_007,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.copper',
    baseCostMoney: 40,
    description: '+15 capacidad máxima de Cobre por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.COPPER,
    icon: 'assets/icons/copper_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_006,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.electric_components',
    baseCostMoney: 80,
    extraCostComponents: 1,
    description: '+5 capacidad máxima de Componentes Eléctricos por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.ELECTRIC_COMPONENTS,
    icon: 'assets/icons/electric_components_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_008,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.circuit_board',
    baseCostMoney: 100,
    description: '+4 capacidad máxima de Placas de Circuito por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.CIRCUIT_BOARD,
    icon: 'assets/icons/circuit_board_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_009,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.hdd',
    baseCostMoney: 150,
    description: '+3 capacidad máxima de Discos Duros por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.HDD,
    icon: 'assets/icons/hdd_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_010,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.screen',
    baseCostMoney: 150,
    description: '+3 capacidad máxima de Pantallas por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.SCREEN,
    icon: 'assets/icons/screen_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_011,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.gpu',
    baseCostMoney: 200,
    description: '+2 capacidad máxima de GPUs por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.GPU,
    icon: 'assets/icons/gpu_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_012,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.smartphone',
    baseCostMoney: 200,
    description: '+2 capacidad máxima de Smartphones por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.SMARTPHONE,
    icon: 'assets/icons/smartphone_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_013,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.laptop',
    baseCostMoney: 250,
    description: '+2 capacidad máxima de Laptops por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.LAPTOP,
    icon: 'assets/icons/laptop_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_014,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.desktop_pc',
    baseCostMoney: 250,
    description: '+2 capacidad máxima de Desktop PCs por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.DESKTOP_PC,
    icon: 'assets/icons/desktop_pc_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_015,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.mining_rig',
    baseCostMoney: 400,
    description: '+1 capacidad máxima de Mining Rigs por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.MINING_RIG,
    icon: 'assets/icons/mining_rig_resource.png',
  },
  {
    id: UpgradeId.UPG_STORE_016,
    category: UpgradeCategory.STORAGE,
    nameKey: 'upgrades.storage.server_rack',
    baseCostMoney: 400,
    description: '+1 capacidad máxima de Server Racks por nivel',
    effectType: 'storage',
    targetResourceId: ResourceType.SERVER_RACK,
    icon: 'assets/icons/server_rack_resource.png',
  },

  // MACHINE SPEED UPGRADES
  // baseCostMoney comes from MACHINE_UPGRADE_CONFIG.BASE_COSTS in game-balance.config.ts — edit there.
  {
    id: UpgradeId.UPG_MACH_001,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.crusher',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.CRUSHER,
    description: 'Aumenta velocidad de Trituradora',
    effectType: 'machine_speed',
    targetMachineId: MachineType.CRUSHER,
    icon: 'assets/cards/crusher_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_002,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.smelter',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.SMELTER,
    description: 'Aumenta velocidad de Fundidora',
    effectType: 'machine_speed',
    targetMachineId: MachineType.SMELTER,
    icon: 'assets/cards/smelter_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_003,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.separator',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.SEPARATOR,
    description: 'Aumenta velocidad de Separador',
    effectType: 'machine_speed',
    targetMachineId: MachineType.SEPARATOR,
    icon: 'assets/cards/separator_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_004,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.assembler',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.ASSEMBLER,
    description: 'Aumenta velocidad de Ensambladora',
    effectType: 'machine_speed',
    targetMachineId: MachineType.ASSEMBLER,
    icon: 'assets/cards/assembler_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_005,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.packager',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.PACKAGER,
    description: 'Aumenta velocidad de Empaquetadora',
    effectType: 'machine_speed',
    targetMachineId: MachineType.PACKAGER,
    icon: 'assets/cards/packager_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_006,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.recycler',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.RECYCLER,
    description: 'Aumenta velocidad de Recicladora',
    effectType: 'machine_speed',
    targetMachineId: MachineType.RECYCLER,
    icon: 'assets/cards/recycler_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_007,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.electric_assembler',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.ELECTRIC_ASSEMBLER,
    description: 'Aumenta velocidad de Ensambladora Eléctrica',
    effectType: 'machine_speed',
    targetMachineId: MachineType.ELECTRIC_ASSEMBLER,
    icon: 'assets/cards/electric_assembler_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_008,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.electric_packager',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.ELECTRIC_PACKAGER,
    description: 'Aumenta velocidad de Empaquetadora Eléctrica',
    effectType: 'machine_speed',
    targetMachineId: MachineType.ELECTRIC_PACKAGER,
    icon: 'assets/cards/electric_packager_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_009,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.pcb_printer',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.PCB_PRINTER,
    description: 'Aumenta velocidad del PCB Printer',
    effectType: 'machine_speed',
    targetMachineId: MachineType.PCB_PRINTER,
    icon: 'assets/cards/pcb_printer_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_010,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.hdd_assembler',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.HDD_ASSEMBLER,
    description: 'Aumenta velocidad del HDD Assembler',
    effectType: 'machine_speed',
    targetMachineId: MachineType.HDD_ASSEMBLER,
    icon: 'assets/cards/hdd_assembler_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_011,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.screen_fabricator',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.SCREEN_FABRICATOR,
    description: 'Aumenta velocidad del Screen Fabricator',
    effectType: 'machine_speed',
    targetMachineId: MachineType.SCREEN_FABRICATOR,
    icon: 'assets/cards/screen_fabricator_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_012,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.gpu_fab',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.GPU_FAB,
    description: 'Aumenta velocidad del GPU Fab',
    effectType: 'machine_speed',
    targetMachineId: MachineType.GPU_FAB,
    icon: 'assets/cards/gpu_fab_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_013,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.smartphone_factory',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.SMARTPHONE_FACTORY,
    description: 'Aumenta velocidad de Smartphone Factory',
    effectType: 'machine_speed',
    targetMachineId: MachineType.SMARTPHONE_FACTORY,
    icon: 'assets/cards/smartphone_factory_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_014,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.laptop_workshop',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.LAPTOP_WORKSHOP,
    description: 'Aumenta velocidad del Laptop Workshop',
    effectType: 'machine_speed',
    targetMachineId: MachineType.LAPTOP_WORKSHOP,
    icon: 'assets/cards/laptop_workshop_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_015,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.pc_builder',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.PC_BUILDER,
    description: 'Aumenta velocidad del PC Builder',
    effectType: 'machine_speed',
    targetMachineId: MachineType.PC_BUILDER,
    icon: 'assets/cards/pc_builder_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_016,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.mining_rig_assembly',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.MINING_RIG_ASSEMBLY,
    description: 'Aumenta velocidad del Mining Rig Assembly',
    effectType: 'machine_speed',
    targetMachineId: MachineType.MINING_RIG_ASSEMBLY,
    icon: 'assets/cards/mining_rig_assembly_card_new_slot.png',
  },
  {
    id: UpgradeId.UPG_MACH_017,
    category: UpgradeCategory.MACHINE,
    nameKey: 'machines.data_center_assembly',
    baseCostMoney: MACHINE_UPGRADE_CONFIG.BASE_COSTS.DATA_CENTER_ASSEMBLY,
    description: 'Aumenta velocidad del Data Center Assembly',
    effectType: 'machine_speed',
    targetMachineId: MachineType.DATA_CENTER_ASSEMBLY,
    icon: 'assets/cards/data_center_assembly_card_new_slot.png',
  },

  // SCRAP GENERATION UPGRADES
  {
    id: UpgradeId.UPG_SCRAP_001,
    category: UpgradeCategory.SCRAP,
    nameKey: 'upgrades.scrap_manual.name',
    baseCostMoney: 95,
    description: '+1 Chatarra adicional por acción manual por nivel',
    effectType: 'scrap_manual',
    icon: 'assets/icons/scrap_resource.png',
  },
  {
    id: UpgradeId.UPG_SCRAP_002,
    category: UpgradeCategory.SCRAP,
    nameKey: 'upgrades.scrap_auto.name',
    baseCostMoney: 115,
    description: 'Genera Chatarra automáticamente por segundo',
    effectType: 'scrap_auto',
    icon: 'assets/icons/scrap_resource.png',
  },
];
